### ISSUE TITLE
Documentation on citing accessions gone

### ISSUE THREAD

**Issue by ikostadi** [enasequence/read_docs#10]
Dear ENA Team,

with one of the more recent updates of the docs, the section that explained which accessions  should or should not be used/published/cited is gone (at least I can't find it anymore). 
Any chance you could incorporate the info in the table under general-guide/accessions.rst

Many thanks and best regards,
Ivo

**Comment by josieburgin** [comment]
Dear Ivo,

Apologies that this section was removed during the reformat of the documentation. As requested, this has now been added to the accessions page:
https://ena-docs.readthedocs.io/en/latest/submit/general-guide/accessions.html

Best,
Josie
