### ISSUE TITLE
Project/Study Hierarchy? Primary Study?

### ISSUE THREAD

**Issue by peterjc** [enasequence/read_docs#16]
# Background

I understand that for typical usage, the study/project hierarchy has been simplified for typical use. Looking at https://ena-docs.readthedocs.io/en/latest/submit/study.html there does not seem to be any documented way to define a sub-study.

Reading ftp://ftp.sra.ebi.ac.uk/meta/xsd/sra_1_5/ENA.project.xsd and ftp://ftp.sra.ebi.ac.uk/meta/xsd/sra_1_5/SRA.study.xsd suggests that the original concept of a project containing one or more studies has been deprecated. There is also mention of having an umbrella project containing one or more submission sequencing projects.

Are new submissions needing nesting expected to define a primary study (``IS_PRIMARY``), and then additional child study entries (using the ``RELATED_STUDIES.STUDY`` to point at the primary study)?

# Usecase

My use case is a wide project using metagenetics of a single target gene, with multiple Illumina sequencing runs (with more added over time to be submitted in future), each containing barcode multiplexed samples. Occasionally a biological sample is resequenced (on a later Illumina run).

# Question

I would like to define any overall grouping, then sub-groups for each sequencing run.

1. Should I use a primary study, with a child study for each Illumina run?
2. Should I use a single study, with the Illumina run information repeated in the metadata of each experiment/run?
3. Should I do something else?

**Comment by sholt6** [comment]
Hi Peter, 
We do have some specific advice on umbrella studies I can send to you. 
Could you please direct your queries to our helpdesk address, datasubs@ebi.ac.uk 
Thanks,
Sam

**Comment by peterjc** [comment]
Email sent - once I've got this working, I'll try to remember to post back to this issue with more specific thoughts on how to make the online documentation clearer. Thanks.

**Comment by sholt6** [comment]
Thanks Peter, I'll pick up your ticket and respond this afternoon

**Comment by sholt6** [comment]
Thanks Peter, I'll pick up your ticket and respond this afternoon
