### ISSUE TITLE
environmental sample versus biosample

### ISSUE THREAD

**Issue by nick-youngblut** [enasequence/read_docs#20]
The docs on submitting MAGs (https://ena-docs.readthedocs.io/en/latest/submit/assembly/metagenome/binned.html?highlight=MAGs) stress that an **Environmental** sample accession must be used, but the difference between and "environmental sample", a "biosample", and "sample" is not explained in that page or really explained at https://ena-docs.readthedocs.io/en/latest/submit/general-guide/accessions.html

**Comment by josieburgin** [comment]
An environmental sample is just a regular ENA registered sample that represents a real life environmental sample. A MAG sample should reference the environmental sample that it was derived from to show the source of the data.
I have now updated the 'Registering MAG samples' section to better explain what an environmental sample is and how these samples should be related: https://ena-docs.readthedocs.io/en/latest/submit/assembly/metagenome/mag.html#registering-mag-samples
