### ISSUE TITLE
Webin File Uploader doesn't see inside External Hard Drive

### ISSUE THREAD

**Issue by adugourd** [enasequence/read_docs#27]
![Screenshot 2020-10-14 at 13 26 07](https://user-images.githubusercontent.com/16302934/95982772-d201ae80-0e20-11eb-9ddd-3e506ae28f90.png)
See screenshot, the external hard drive appears empty even though my folders with data are there.

**Comment by sholt6** [comment]
Hi Aurelien,
Thanks for your report - could you please submit this to our helpdesk, along with some more detailed information on how your hard drive looks?
https://www.ebi.ac.uk/ena/browser/support
Thanks,
Sam
