### ISSUE TITLE
Missing docs on portal API search by POST (doesn't take JSON?)

### ISSUE THREAD

**Issue by shamseen** [enasequence/read_docs#31]
Looking through readthedocs and the pdf, I haven't found how to structure the call without curl (I'm using javascript and `axios`). 

All I know is that JSON isn't supported since I couldn't use the JSON shown by any of my rules.

**Comment by sholt6** [comment]
Hi @shamseen , thanks for your feedback

Could you please create a ticket with our helpdesk to discuss programmatic searches of ENA data?
https://www.ebi.ac.uk/ena/browser/support

Thanks and best,
Sam

**Comment by shamseen** [comment]
Hey, you're the guy that did the introduction video on ENA!

**Comment by sholt6** [comment]
Haha, that's me! Hope you found it useful 

Fair enough, it's just a lot easier to track these conversations through our ticketing system, as well as making sure they get seen by the right person

**Comment by shamseen** [comment]
No worries. But could you at least tell me how to make a post request? I honestly don't know where to find those instructions.

**Comment by sholt6** [comment]
I'm not sure how to, which is why we use the helpdesk system: your ticket is with my colleague, who'll answer soon. They also indicated that they'll update the docs with this information too.
