### ISSUE TITLE
Update Permitted values for instrument

### ISSUE THREAD

**Issue by paulineauffret** [enasequence/read_docs#63]
Hello,
We have noticed that in the [ENA Browser](https://www.ebi.ac.uk/ena/browser/advanced-search), we can select "Sequel II" and "Sequel IIe" as Instrument Platform values in an advanced search. Unfortunatelly, these new values do not appear in the ["Permitted values for instrument" section of the documentation](https://ena-docs.readthedocs.io/en/latest/submit/reads/webin-cli.html?highlight=Miseq#permitted-values-for-instrument).
Is it possible to update the documentation with newly accepted values ? AS well as the Permitted values for platform.
Thank you very much,
Pauline

**Comment by Woolly-at-EBI** [comment]
These were added to the documentation in 2023m, along with many new platforms and other instruments.
Sorry for not having seem this GitHub issue until now. (message to self, to check for similar ones more regularly.
Thanks for having reported it this way.
